### PR TITLE
Remove unneeded feature declarations

### PR DESCRIPTION
**Pull request by joshuawarner32**
This allows this crate to compile on stable rust, 1.48. Previously, I was seeing these errors:

```
﻿error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/joshw/.cargo/registry/src/github.com-1ecc6299db9ec823/doh-dns-0.2.0/src/lib.rs:59:1
   |
59 | #![feature(proc_macro_hygiene)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/joshw/.cargo/registry/src/github.com-1ecc6299db9ec823/doh-dns-0.2.0/src/lib.rs:60:1
   |
60 | #![feature(stmt_expr_attributes)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It's unclear to me why the code originally required these features? If they were stabilized I would expect a different error, about the feature decl not beeing needed.

### CODE REVIEW

**Comment by joshuawarner32** [comment]
For reference, these are the tracking issues for the two features:

* https://github.com/rust-lang/rust/issues/54727
* https://github.com/rust-lang/rust/issues/15701

As of writing, they're both open, which makes me suspect either this library no longer requires these features, or it never did (I haven't investigated to understand which it is / why)
